name: Check commands
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install beet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with beet
        run: |
          beet build
